package com.medicalsystem.backend.model

enum class AssessmentScaleType {
    MENTAL_HEALTH_ASSESSMENT,
    SLEEP_ASSESSMENT,
    DIGITAL_HABITS_DAILY_BEHAVIORS_ASSESSMENT,
    SOCIAL_ENVIRONMENT_SUPPORT_ASSESSMENT,
    SELF_REGULATION_PERSONALITY_ASSESSMENT,
    FAMILY_BACKGROUND_EARLY_EXPERIENCES_ASSESSMENT,
    CLINICAL_SCREENING_NEURODIVERGENCE_ASSESSMENT,
    PERSONALITY_COPING_OUTLOOK_ASSESSMENT
}
