package com.medicalsystem.backend.model

enum class NotificationMessageCode(val code: Int) {
    REFERRAL_INITIATED(1),
    REFERRAL_STATUS_CHANGED(2),
    APPOINTMENT_SCHEDULED(3),
    EVALUATION_COMPLETED(4),
    REFERRAL_SUBMITTED_STUDENT(5),
    REFERRAL_SUBMITTED_INITIATOR(6),
    REFERRAL_REQUIRES_REVIEW_HC(7),
    REFERRAL_CREATED_FOR_STUDENT_TEACHER(8),
    REFERRAL_APPROVED_BY_HC_TEACHER(9),
    REFERRAL_APPROVED_BY_HC_STUDENT(10),
    REFERRAL_NEEDS_TRIAGE_ADMIN(11),
    REFERRAL_DOCTOR_ASSIGNED_DOCTOR(12),
    REFERRAL_DOCTOR_ASSIGNED_TEACHER(13),
    REFERRAL_DOCTOR_ASSIGNED_STUDENT(14),
    REFERRAL_DOCTOR_ASSIGNED_HC(15),
    REFERRAL_SCHEDULED_STUDENT(16),
    REFERRAL_SCHEDULED_TEACHER(17),
    REFERRAL_SCHEDULED_HC(18),
    REFERRAL_SCHEDULED_ADMIN(19),
    REFERRAL_FEEDBACK_SUBMITTED_HC(20),
    REFERRAL_FEEDBACK_SUBMITTED_TEACHER(21),
    REFERRAL_FEEDBACK_SUBMITTED_ADMIN(22),
    REFERRAL_FEEDBACK_SUBMITTED_STUDENT(23),
    REFERRAL_CLOSED_TEACHER(24),
    REFERRAL_CLOSED_STUDENT(25),
    REFERRAL_REJECTED_TEACHER(26),
    REFERRAL_REJECTED_STUDENT(27),
    REFERRAL_REJECTED_HC(28),
    REFERRAL_NEEDS_REASSIGNMENT_ADMIN(29),
    REFERRAL_RECALLED_HC(30),
    ASSESSMENT_ASSIGNED_STUDENT(31),
    ASSESSMENT_COMPLETED_TEACHER(32),
    ASSESSMENT_HIGH_RISK_ALERT_HC(33);

    companion object {
        fun fromCode(code: Int): NotificationMessageCode = entries.find { it.code == code }
            ?: throw IllegalArgumentException("Unknown NotificationMessageCode code: $code")
    }
}
