package com.medicalsystem.backend.model

enum class TestResultName {
    PHQ_9,
    GAD_7,
    BDI_II,
    BAI,
    PSQI,
    ISS,
    ESS,
    SCL_90,
    ANNUAL_COMPREHENSIVE,
    APQ_9_FATHER,
    APQ_9_MOTHER,
    SLEEP_DISORDER,
    COMPREHENSIVE_MENTAL,
    MENTAL_HEALTH_ASSESSMENT,
    SLEEP_ASSESSMENT,
    DIGITAL_HABITS_DAILY_BEHAVIORS_ASSESSMENT,
    SOCIAL_ENVIRONMENT_SUPPORT_ASSESSMENT,
    SELF_REGULATION_PERSONALITY_ASSESSMENT,
    FAMILY_BACKGROUND_EARLY_EXPERIENCES_ASSESSMENT,
    CLINICAL_SCREENING_NEURODIVERGENCE_ASSESSMENT,
    PERSONALITY_COPING_OUTLOOK_ASSESSMENT
}
