spring.datasource.url=jdbc:h2:mem:medical_db;NON_KEYWORDS=YEAR;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
server.error.include-message=always
server.error.include-stacktrace=always
spring.jpa.open-in-view=false

storage.s3.endpoint-internal=http://localhost:9000
storage.s3.endpoint-external=http://localhost:9000
storage.s3.access-key=minioadmin
storage.s3.secret-key=miniopassword
storage.s3.bucket=medical-attachments
storage.s3.region=us-east-1
