package com.medicalsystem.backend.repository

import com.medicalsystem.backend.entity.StudentEntity
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class StudentRepositoryTest {

    @Autowired
    private lateinit var studentRepository: StudentRepository

    @Autowired
    private lateinit var collegeRepository: com.medicalsystem.backend.repository.CollegeRepository

    @Autowired
    private lateinit var majorRepository: com.medicalsystem.backend.repository.MajorRepository

    @Test
    fun `should save and find student by student number`() {
        val college = collegeRepository.save(com.medicalsystem.backend.entity.CollegeEntity(name = "Engineering"))
        val major = majorRepository.save(com.medicalsystem.backend.entity.MajorEntity(name = "CS", college = college))
        val student = StudentEntity(
            studentNumber = "S999",
            name = "Test Student",
            major = major,
            enrollmentDate = java.time.LocalDate.of(2023, 9, 1),
            riskStatus = com.medicalsystem.backend.entity.RiskStatus.LOW
        )
        
        studentRepository.save(student)
        
        val found = studentRepository.findByStudentNumber("S999")
        
        assertNotNull(found)
        assertEquals("Test Student", found?.name)
        assertNotNull(found?.id) // ID should be auto-generated by H2
    }
}
