package com.medicalsystem.backend.repository

import com.medicalsystem.backend.entity.StudentEntity
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class StudentRepositoryTest {

    @Autowired
    private lateinit var studentRepository: StudentRepository

    @Test
    fun `should save and find student by student number`() {
        val student = StudentEntity(
            studentNumber = "S999",
            name = "Test Student",
            major = "Testing",
            year = "Year 4",
            status = "Active"
        )
        
        studentRepository.save(student)
        
        val found = studentRepository.findByStudentNumber("S999")
        
        assertNotNull(found)
        assertEquals("Test Student", found?.name)
        assertNotNull(found?.id) // ID should be auto-generated by H2
    }
}
